### ISSUE TITLE
After setup, Dashboard doesn't actually retrieve data (or appears to not)

### ISSUE THREAD

**Issue by abritocamtech** [ericpopivker/FogBugz-Project-Dashboard#1]
I installed the app as stated, re-set the server and user to our internal system in AppSettings.config, but when viewing the front page, I get the spinning wheel and the progressbar that says getting projects and milestones stays empty.  Does this application require a secure fogbugz connection (https?)  it's not configured that way here.

**Comment by ericpopivker** [comment]
Hi,

Can you look for  log4net.log in root dir of your web app.  Copy paste the last exception to this chat.

**Comment by abritocamtech** [comment]
This is an internal computer, so you can't get to it from the outside, but both machines are.

exception:

2014-04-11 09:49:31,283 [31] ERROR MvcApplication.Application_Error - Agent Exception
System.AggregateException: One or more errors occurred. ---> System.Net.CookieException: The 'Domain'='http://bed-srv-fogbugz.gsig.com' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.Add(Cookie cookie)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.GetGroupsHtmlNode(String token, String fogBugzUrl)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.GetGroups(String fogBugzUrl, String token)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.Load(String fogBugzUrl, String token, Boolean& isAdmin)
   at FogBugzPd.Core.FogBugzApi.FogBugzGateway.<>c__DisplayClass8.<LoadFogBugzAgentCache>b__7()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at FogBugzPd.Core.FogBugzApi.FogBugzGateway.LoadFogBugzAgentCache()
   at FogBugzPd.Core.FogBugzApi.FogBugzGateway.get_ClientCache()
   at FogBugzPd.Web.Controllers.ProjectController.CreateListViewModel()
   at FogBugzPd.Web.Controllers.ProjectController.AsyncList(Int32 timeOffest)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at System.Web.Mvc.Controller.ExecuteCore()
   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass6.<>c__DisplayClassb.<BeginProcessRequest>b__5()
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass1.<MakeVoidDelegate>b__0()
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
---> (Inner Exception #0) System.Net.CookieException: The 'Domain'='http://bed-srv-fogbugz.gsig.com' part of the cookie is invalid.
   at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
   at System.Net.CookieContainer.Add(Cookie cookie)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.GetGroupsHtmlNode(String token, String fogBugzUrl)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.GetGroups(String fogBugzUrl, String token)
   at FogBugzPd.Core.FogBugzApi.FbScheduleLoader.Load(String fogBugzUrl, String token, Boolean& isAdmin)
   at FogBugzPd.Core.FogBugzApi.FogBugzGateway.<>c__DisplayClass8.<LoadFogBugzAgentCache>b__7()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by ericpopivker** [comment]
Hi,

Please try version 2.0.1:
https://github.com/ericpopivker/FogBugz-Project-Dashboard/releases/tag/2.0.1

The issue with http should be fixed.

Eric

**Comment by abritocamtech** [comment]
My error changed now... 
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 172.28.215.184:443

I am not specifying https in the config because the machine FB is on didn't enable it, is there a way to tell FBDash to not use https?  (if not, I'll just get IT to fix our machine, it should work with https...)
